apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
    spec:
      containers:
      - name: python-backend
        image: 10.98.196.224:80/python-backend:18270e51a1fe74297f9b14d76bf61b6a8c87a5ee
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: python-backend-svc
  namespace: apps
spec:
  selector:
    app: python-backend
  ports:
  - port: 80
    targetPort: 5000
